export const initialListItem = [
  {
    id: 1,
    name: "backpack",
    title: "",
    price: "",
    description: "",
    imgSrc: null,
    cartSum: 0,
  },
  {
    id: 2,
    name: "premium-tshirt",
    title: "",
    price: "",
    description: "",
    imgSrc: null,
    cartSum: 0,
  },
  {
    id: 3,
    name: "jacket",
    title: "",
    price: "",
    description: "",
    imgSrc: null,
    cartSum: 0,
  },
  {
    id: 4,
    name: "tshirt",
    title: "",
    price: "",
    description: "",
    imgSrc: null,
    cartSum: 0,
  },
  {
    id: 15,
    name: "coats",
    title: "",
    price: "",
    description: "",
    imgSrc: null,
    cartSum: 0,
  },
  {
    id: 16,
    name: "leather-jacket",
    title: "",
    price: "",
    description: "",
    imgSrc: null,
    cartSum: 0,
  },
];
